include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true

  errors:
    invalid_annotation_target: ignore
    invalid_use_of_protected_member: error
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    parameter_assignments: error
    sort_unnamed_constructors_first: ignore

  exclude:
    - lib/**.config.dart
    - lib/**/*.g.dart
    - lib/**/*.gr.dart
    - lib/**/*.freezed.dart
    - lib/config/themes.dart

linter:
  rules:
    omit_local_variable_types: true
    prefer_relative_imports: false
    prefer_single_quotes: true
    sort_pub_dependencies: true
    avoid_redundant_argument_values: true
    close_sinks: true
    cancel_subscriptions: true
    no_logic_in_create_state: true
